"""Initial

Revision ID: 1149d79afefe
Revises: 7afe8b22d57d
Create Date: 2023-01-10 22:37:31.224766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1149d79afefe'
down_revision = '7afe8b22d57d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('video_name', sa.String(), nullable=False),
    sa.Column('video_description', sa.Text(), nullable=False),
    sa.Column('date_published', sa.DATE(), nullable=True),
    sa.Column('number_views', sa.Integer(), nullable=True),
    sa.Column('number_likes', sa.Integer(), nullable=True),
    sa.Column('number_dislikes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
