"""Initial

Revision ID: b8db715835b6
Revises: 1149d79afefe
Create Date: 2023-01-10 22:40:35.995472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8db715835b6'
down_revision = '1149d79afefe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_cover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'video_cover')
    # ### end Alembic commands ###
